In [2]:
import re
text="python is easy"
result=re.search("python", text)
print(result)

<re.Match object; span=(0, 6), match='python'>


In [4]:
import  re
text="i have 10 book 20 pens"
result=re.findall(r"\d",text)
print(result)

['1', '0', '2', '0']


In [6]:
import re
text="i have 10 books 20 pens"
result=re.findall(r"\d+",text)
print(result)

['10', '20']


In [8]:
import re
text="python programing"
result=re.match("python",text)
print(result.group())

python


In [9]:
import re
text="apple,orange,mango"
result=re.split(",",text)
print(result)

['apple', 'orange', 'mango']


In [13]:
import re
text="java programing"
result=re.match("java",text)
print(result.group())

java


In [3]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr[[1,3]])

[20 40]


In [4]:
import numpy as np
a=np.array(["Ram","ravi","sura","amulya"])
print(a[1],a[3])


ravi amulya


In [12]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [16]:
marks=np.array([87,93,90,56,83,91])
print(marks[marks>88])

[93 90 91]


In [17]:
for i in [10,20,30,440]:
    print(i)

10
20
30
440


In [19]:
arr=np.array([10,20,30,40])
for i in arr:
    print(i)
    

10
20
30
40


In [23]:
marks=np.array([[10,20],[30,40],[50,60],[70,80]])
for i in marks:
    print(i)

[10 20]
[30 40]
[50 60]
[70 80]


In [24]:
arr=np.array([[10,20],[30,40],[50,60],[70,80]])
for i in arr:
    print(i)

[10 20]
[30 40]
[50 60]
[70 80]


In [28]:
arr=np.array([[10,20],[30,40],[50,60],[70,80]])
for row in arr:
    print(row)

[10 20]
[30 40]
[50 60]
[70 80]


In [26]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in arr:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [32]:
for i in np.nditer(arr):
 print(i)

10
20
30
40
50
60
70
80


In [50]:
arr=np.array([10,20,30,40,30,50])
x=np.where(arr==30)
print(x)

(array([2, 4], dtype=int64),)


In [57]:
a=np.array([10,20,30])
b=np.array([40,50,60])
c=np.concatenate([a,b])
print(c)

[10 20 30 40 50 60]


In [62]:
arr1=np.array([4,5,6])
arr2=np.array([7,8,9])
print(arr1+arr2)

[11 13 15]


In [67]:
arr=np.array([20,4,5,6,7,8])
x=np.sort(arr)
print(x)

[ 4  5  6  7  8 20]


In [69]:
marks=np.array([89,90,87,93,97])
print(marks[marks>=50])

[89 90 87 93 97]


In [71]:
arr=np.array([10,20,30])
print(np.sum(a))

60


In [76]:
arr=np.array([10,20,30])
print(np.max(a))
print(np.min(a))
print(np.mean(a))

30
10
20.0


In [79]:
print(np.power(arr,2))


[100 400 900]
