In [2]:
name=["sravani","Raj","Rahul"]
it=iter(name)
print(next(it))
print(next(it))
print(next(it))

sravani
Raj
Rahul


In [3]:
marks=[22,34,45,56,66,52]
it=iter(marks)
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))


22
34
45
56
66


In [8]:
def numbers():
  yield 1
  yield 2
  yield 3
gen = numbers()
print(next(gen))
print(next(gen))
print(next(gen))



1
2
3


In [3]:
file = open("demo.txt","w")
file.write("Hello student")
file.close()  

In [4]:
file=open("demo.txt" , "r" )
conent=file.read()
print(conent)
file.close()

Hello student


In [1]:
list=[1,2,3,4]
print(list[3])

4


In [6]:
try:
    num=10
    print(num/0)
except ZeroDivisionError:
    print("cannot divide by zero")
    

cannot divide by zero


In [7]:
try:
    file=open("demo,text","r")
    content=file.read()
    priny(content)
    file.close()
except :
    print("file not found")

file not found


In [ ]:
try:
    a=int(input("Enter the age:"))
except valueError:
    print("it is not a integer")

In [1]:
print("Hello world")

Hello world


In [2]:
a= 10
b= 20
a = a+b
b = a-b
a=  a-b
print("a =",a)
print("b =",b)

a = 20
b = 10


In [14]:
p= float(input("Enter principal Ammount:"))
r= float(input("Enter Rate of Interst :"))
t =float(input("Enter Time :"))
si = (p* r * t)/100
print("simple Interest =",si)

Enter principal Ammount: 10000
Enter Rate of Interst :  5
Enter Time :  2


simple Interest = 1000.0


In [15]:
num = int(input("Enter a number : "))
if num % 2 == 0:
    print("Even")
else:
    print("odd")
    

Enter a number :  5


odd


In [3]:
 a = int(input("Enter frist number :"))
 b = int(input("Enter second number: "))
 c = int(input("Enter thrid number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else: 
    largest = c
 print("Largest number =",largest)

Enter frist number : 2
Enter second number:  8
Enter thrid number:  6


Largest number = 8


In [1]:
marks = int(input("Enter marks: "))
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade =  "C"
elif marks >= 40:
    grade = "D"
else:
    grade = "F"
print("Grade =",grade) 

Enter marks:  75


Grade = B


In [ ]:
num = input(input("Enter a number:"))
if num % 5==0 and num % 11 == 0:
    print("The number is didvvisible by both 5 and 11")
else:
    print("The number is not didvisble by both 5 and 11")


In [ ]:
num = int(input("Enter a number: "))
count = len(str(abs(num)))
print("Number of digits =",count)

In [9]:
try:
    name=input("Enter the number")
    print(10/num)
except ValueError:
    print("Invalid Input")
except ZeroDivisionError:
   print("cannot divided by Zero")
else:
   print("program execute successfully")
finally:
    print("This block is going to execute everytime")
    

Enter the number r


This block is going to execute everytime


NameError: name 'num' is not defined

In [22]:
age=int(input("Enter the age"))
if age<18:
   FalseException("you are not eligible for vote")
print("Eligible")

Enter the age 18


Eligible


In [3]:
try:
    a=int(input("enter the number:"))
    b=int(input("enter the number:"))
    print(a/b)
except ZeroDivisionError:
    print("invalid")
except ValueError:
    print("invalid")
else:
    print("program execute successfully")
finally:
    print("thank you")

enter the number: 12
enter the number: 12


1.0
program execute successfully
thank you


In [7]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [8]:
import numpy as np
arr=np.array([20,30,490,50])
print(arr)

[20 30 40 50]


In [12]:
arr=np.array([[10,20],[20,30],[40,88]])
print(arr)

[[10 20]
 [20 30]
 [40 88]]
