In [10]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]]


In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.hstack((a,b)))

[1 2 3 5 6 7]


In [12]:
arr=np.array([2,3,4,5])
print(arr +5)

[ 7  8  9 10]


In [15]:
arr=np.array([[2,3,1],[4,5,8]])
print(arr +[5,10,3])

[[ 7 13  4]
 [ 9 15 11]]


In [16]:
arr=np.array([[2,3],[5,6]])
print(arr +[8,9])

[[10 12]
 [13 15]]
